### ISSUE TITLE
Issue on page /index.html

### ISSUE THREAD

**Issue by JuergHauser** [inlab-geo/cofi#44]
The tree figure uses PyMC4. I would suggest to just use PyMC - See https://github.com/pymc-devs/pymc4

**Comment by jwhhh** [comment]
They [released the new pmc4](https://github.com/pymc-devs/pymc/releases/tag/v4.0.0) 5 days ago. But yes, I agree that we should not include the version number as they've also stopped including it (e.g. `import pymc as pm` instead of `import pymc4 as pm`)
