### ISSUE TITLE
Problem with InvalidOptionError when running gravity_density.ipynb

### ISSUE THREAD

**Issue by td-jones** [inlab-geo/cofi#72]
#Description
When running the 3rd code block of gravity_density.ipynb, grav_problem.set_data_mistfit() throws up an error no matter the input. Default here is "L2". A function here seems to be self referential: "Invalid_option" for "set_data_misfit" is set to variable name "data_misfit".

#To reproduce
Run first three blocks of gravity_density.ipynb

#Expected behaviour
Code should return the following error:

---------------------------------------------------------------------------
```
InvalidOptionError                        Traceback (most recent call last)
Cell In [6], line 46
     43 grav_problem.set_regularization(reg_l1, epsilon, args=[W])
     45 # Use default L2 misfit
---> 46 grav_problem.set_data_misfit("L2")
     47 grav_problem.set_initial_model(Starting_model3)
     49 # Set gradient, in hope of helping optimisers converge better

File ~/Projects/inlab_forked/venv/lib/python3.10/site-packages/cofi/base_problem.py:954, in BaseProblem.set_data_misfit(self, data_misfit, args, kwargs)
    950         self.data_misfit = _FunctionWrapper(
    951             "data_misfit", self._data_misfit_squared_error, autogen=True
    952         )
    953     else:
--> 954         raise InvalidOptionError(
    955             name="data misfit", invalid_option=data_misfit, valid_options=["L2"]
    956         )
    957 else:
    958     self.data_misfit = _FunctionWrapper(
    959         "data_misfit", data_misfit, args, kwargs
    960     )

InvalidOptionError: the data misfit you've entered ('L2') is invalid, please choose from the following: ['L2'].
```

**Comment by jwhhh** [comment]
Hi, thanks for reporting the issue!

Sorry for the confusion here. We've changed the keyword from `L2` to `squared error` since it's strictly not the norm (but we forgot to change the error message, sorry!). Please replace `L2` with `squared error` and it should work. 

We'll update the next release of `cofi` with this error message fixed within this week. Will update `cofi-examples` soon as well.
